remote_theme: sujaykundu777/devlopr-jekyll  # Don't touch ( required for this theme)

# Edit your preferences below 
title: Yuvraj Bisht
subtitle: Game Developer,Software Engineer
description: >- # this means to ignore newlines until "baseurl:"
  Yuvraj is a software engineer with interests in Game Development

url: "https://yuvraj133.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    - text: About Me
      url: /about
    - text: Contact Me
      url : /contact
    - text: Sample Page
      url: /sample-page

# Edit these details 

author_logo: profile.png
author: Yuvraj 
author_bio: Hi, My Name is Yuvraj. Game Developer and a Software Engineer. I live in Uttarakhand, India
author_email: "yuvrajbisht13@gmail.com"
author_location: India
author_website_url: "http://yuvrajbisht.com"

author_work_experiences: 
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: programmingebooks.png
                project_title: Programming Ebooks
                project_description: A Platform to easily find and read programming books
                project_url: https://programmingebooks.com
                visibility: true

# social links
twitter_username: 
github_username:  Yuvraj133
facebook_username: 
linkedin_username: 
behance_username: 
instagram_username: 
medium_username:
telegram_username: 
dribbble_username: 
flickr_username: 

#for comments using disqus
disqus_shortname: 

# wakatime username
wakatime_username: 

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics:

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

'


