---
title: Yuvraj Singh Bisht
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
remote_theme: sujaykundu777/devlopr-jekyll
subtitle: Game Developer, Software Engineer
description: Yuvraj is a software engineer with interests in Game Development
url: http://yuvrajbisht.com
baseurl: 
urls:
- text: Blog
  url: "/blog"
- text: About Me
  url: "/about"
- text: Contact Me
  url: "/contact"
- text: Sample Page
  url: "/sample-page"
author_logo: profile.jpg
author: Yuvraj
author_bio: Hi, My Name is Yuvraj. Game Developer and a Software Engineer. I live
  in Uttarakhand, India
author_email: yuvrajbisht33@gmail.com
author_location: India
author_website_url: http://yuvrajbisht.com
author_work_experiences:
- company_name: Digifuse
  company_logo: digifuse.jpg
  company_url: http://www.digifuse.co.in/
  designation: Marketing & Business Development Intern
  description: Practically Experienced “Business Development Strategies” various aspects
    of marketing and the working of Marketing/Advertising company.
  visibility: true
- company_name: Parallel Reality Ltd.
  company_logo: parallelreality.jpg
  company_url: http://parallelreality.co.uk/
  designation: Part-time Software Developer
  description: Practically Experienced “Game Development”, “Quality Control” and “Quality
    assurance” aspects of the project in the company.
  visibility: true
author_education_details:
- college_logo: mit.png
  college_name: MIT
  college_url: https://mit.org
  college_degree: CS Engineer
  description: Bachelor of Technology
  visibility: true
author_project_details:
- project_thumbnail: gamershub.png
  project_title: Gamers Hub
  project_description: A Platform built for Gamers and Game Devs
  project_url: https://gamershub.in
  visibility: true
- project_thumbnail: programmingebooks.png
  project_title: Programming Ebooks
  project_description: A Platform to easily find and read programming books
  project_url: https://programmingebooks.com
  visibility: true
twitter_username: 
github_username: Yuvraj133
facebook_username: 
linkedin_username: 
behance_username: 
instagram_username: 
medium_username: 
telegram_username: 
dribbble_username: 
flickr_username: 
disqus_shortname: 
wakatime_username: 
markdown: kramdown
highlighter: rouge
permalink: pretty
google_analytics: 
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
plugins:
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-remote-theme
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
  endings: all
  ignore:
    envs:
    - development
